apiVersion: v1
kind: Pod
metadata:
  name: flex-nas-pod001 
spec:
  containers:
    - name: "nginx-flexvolume-nas-pvc"
      image: "nginx"
      volumeMounts:
          - name: pvc-nas
            mountPath: "/data"
  volumes:
  - name: pvc-nas
    persistentVolumeClaim:
        claimName: flexnaspvc2g001
