apiVersion: v1
kind: Pod
metadata:
  name: pod-flex-001
  namespace: default 		# 将pod部署在default命名空间内
spec:
  nodeName: worker001		# 设置了绑定node节点，便于测试观察结果                                    
  containers:
    - name: "pod-flex-001"
      image: "registry-bj.capitalonline.net/cck/python:3.8"
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-ce", "touch /data/file" ]
      volumeMounts:
        - name: pvc-nas
          mountPath: "/data"
  volumes:
  - name: pvc-nas
    persistentVolumeClaim:
        claimName: pvc-flex-001