apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flex-001
  labels:
    name: "pv001"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "cds/nas"
    options:
      server: "164.52.43.137"
      path: "/nfsshare/static"
      vers: "4.0"
      mode: "755"